apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'go-server'
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'git@github.com:dpentim78/gitops-sample.git'
    targetRevision: HEAD
    path: chart
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true




# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: 'go-server'
# spec:
#   destination:
#     name: 'in-cluster'
#     namespace: 'prod'
#   source:
#     path: 'chart'
#     repoURL: 'https://github.com/RinkiyaKeDad/gitops-sample'
#     targetRevision: HEAD
#     helm:
#       valueFiles:
#       - values.yaml
#   project: 'default'
#   syncPolicy:
#     syncOptions:
#       - CreateNamespace=true